### ISSUE TITLE
为什么不用std::thread而用pthread实现呢？

### ISSUE THREAD

**Issue by choleraehyq** [Leviathan1995/mask_recognition#1]
两者在效率上没有明显差别，std::thread是跨平台的标准库组件。

说起来我也写过一个类似的https://github.com/choleraehyq/libconds/blob/master/src/threadPool/threadPool.h
可以交流一下。

**Comment by leviathan0992** [comment]
这两个在一些方面用起来差不多，但是thread为了跨平台基本上就是阉割各个原生实现的子集，api不如pthread多，pthread是操作系统的标准，thread只是c++语言标准

**Comment by choleraehyq** [comment]
这有两个关于pthread和thread的讨论，仅供参考。
http://stackoverflow.com/questions/19209214/if-i-have-pthread-code-on-linux-is-there-an-advantage-to-implementing-the-same
https://segmentfault.com/q/1010000002426368

**Comment by leviathan0992** [comment]
呃，我觉得两个各有长处吧，看个人喜好，反正是写着玩

**Comment by foxyz** [comment]
底层区别还是比较大的，按照C++大神meyers说法：目前的大多数厂商使用了std::thread同样的机制而不是pthread
